### PR TITLE
Add client assertion authentication

### PR DESCRIPTION
**Pull request by ycrumeyrolle**
- [x] Token endpoint
- [ ] Introspection endpoint
- [ ] Revocation endpoint

Related to #61

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks!

couple of comments (and that's why it is always better to start a discussion first)

* I don't want a dependency on the Microsoft JWT lib
* I'd rather have a more general way of doing that - e.g. an easy way to ammend the form body

(and you broke the build ;)

So maybe start over and do a proposal first.

**Comment by leastprivilege** [comment]
Maybe some generic callback when creating the POST body would be a better solution.

**Comment by leastprivilege** [comment]
You probably want to start over. Agreed?

**Comment by ycrumeyrolle** [comment]
At least, we some code to discuss :)

> I don't want a dependency on the Microsoft JWT lib

Another lib?
If not lib, the hard part will be the signing algorithm probably limited to HS256 and RS256.

> I'd rather have a more general way of doing that - e.g. an easy way to ammend the form body

Like here ? https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/TokenClientExtensions.cs#L251

**Comment by ycrumeyrolle** [comment]
I will open an issue dedicated for this discussion.

**Comment by leastprivilege** [comment]
I will open an issue so we can discuss this.

**Pull request closed without merging**
