### PR TITLE
Add issuer to Instrospect scope claims.

### PR DESCRIPTION
**Pull request by putnap**
I'm not sure about line 29. I'm considering that it should be Single, not SingleOrDefault, because I assume issuer should always be part of introspect response.

This PR solves #357 issue.

### CODE REVIEW

**Comment by leastprivilege** [comment]
iss is optional
https://tools.ietf.org/html/rfc7662#section-2.2

Why are you only adding the issuer to scope claims? what about the other claims?

**Comment by putnap** [comment]
Updated to include issuer in all of the claims created.

**Comment by leastprivilege** [comment]
You should default issuer to LOCAL AUTHORITY - in case it is missing.

**Comment by putnap** [comment]
It's already done by Claim class itself.

**Comment by leastprivilege** [comment]
OK. Thanks! Will release a new version later today.

**Pull request merged**
