### PR TITLE
Make Hawk buildable with either .NET 452 or NETSTANDARD 1.6

### PR DESCRIPTION
**Pull request by iancooper**
Feel free to reject this PR, for now it is a courtesy. I needed the Hawk suppot from Identity Model to move forward with Brighter https://github.com/iancooper/Paramore

It builds, but does not offer all the functionality required for a working version, yet. I need a build to get tests to pass, to be able to then move forward with debugging this and adding some missing pipeline support.

If you are interested I can resubmit when we get it working

I also appreciate that this repository is experimental.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Hey Ian - 

I want to keep the v2 version of identitymodel as small as possible.

If you are interested in maintaining a netstandard compat version of Hawk, we could put that into a separate repo.

**Comment by iancooper** [comment]
@leastprivilege  Love to. Do you want to create a repo I can use, then I can push the contribution there? (Assuming you want to hold onto it under your GitHub, happy to host if you don't).

**Comment by leastprivilege** [comment]
tbh - i don't have the cycles to maintain anything more than I already do - this even includes putting the repo under our organization.

I am happy if you want to take over the Hawk code and maintain it.

**Comment by iancooper** [comment]
Will do

**Pull request closed without merging**
