### PR TITLE
Adding TokenRefreshed event to RefreshTokenHandler

### PR DESCRIPTION
**Pull request by swisszeni**
As proposed in #71

### CODE REVIEW

**Comment by leastprivilege** [comment]
The concern here is that the code that handles the event could block. Maybe it's better to spin up a task for that.

**Comment by swisszeni** [comment]
Indeed, but I think this should be the concern of the called code and not the lib. As only the handling code knows if it may be blocking.

If you think different, I'll add a task.

**Comment by leastprivilege** [comment]
I think we should do it in fire & forget style.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
