### PR TITLE
Added ClientAssertion ValueProvider.

### PR DESCRIPTION
**Pull request by vit100**
Related to : https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/69#issue-561968169.

### CODE REVIEW

**Comment by leastprivilege** [comment]
I am not sure that the base-library is the place to fix this...but need to think about it.

**Comment by vit100** [comment]
With this patch to the library I tried to keep designed functionality and compatibility with existing code, but it also solves important issue. 
Probably you can find another way to fix it in more elegant way.
What are plans for this PR? Should I wait merge or do my custom code in my project?

**Comment by leastprivilege** [comment]
see the aspnetcore repo...

**Comment by vit100** [comment]
Hey Dominick,
With the latest patch in `IdentityModel.AspNetCore` (abstraction of configuration) problem is kind of fixed with ClientAssertion.
What bothers me that in order to modify `ClientCredentialsTokenRequest` user has to inherit `DefaultTokenClientConfigurationService`, register new implementation in DI, override

`public async override Task<ClientCredentialsTokenRequest> GetClientCredentialsRequestAsync(string clientName)`

May be it does make sense to follow my approach in this PR - instead of public string Value { get; set; }
use public Func<string> ValueProvider { get; set; } and mark Value property as Obsolete.
In this case user will not be forced to to all that steps above.

**Comment by leastprivilege** [comment]
I decided against it. This repo here only provider primitives. If you need higher level functionality (like e.g. the .AspNetCore repo) you need to build it there.

Also a simple Func<string> is probably not enough for what you need in real apps. It's not async, you probably need access to config, logging etc...

Thanks for interacting though!

**Pull request closed without merging**
