### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@leastprivilege I am waiting for you to merge this.

**Comment by leastprivilege** [comment]
There are conflicts. Could you rebase?

**Comment by vanillajonathan** [comment]
I don't know how to do that. The "Allow edits by maintainers" box is ticked. Could you rebase or resolve the conflict?

**Comment by vanillajonathan** [comment]
I think I resolved it now.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
