### PR TITLE
Don't wrap OperationCanceledException in a protocol response

### LINKED ISSUE #176: Cancellation exception shouldn't be wrapped in a TokenResponse
Currently, `TokenClient` [wraps all exceptions in a `TokenResponse`](https://github.com/IdentityModel/IdentityModel2/blob/1a0e6ba202ef034a20062359f8e997606ea216a7/src/Client/Old/TokenClient.cs#L177-L184). However, certain exceptions should be allowed to bubble up until caught, in particular `OperationCanceledException`. It's really counter-intuitive to have to inspect the `TokenResponse.Exception` to detect if the operation was canceled.

So the code should probably be something like this:

            try
            {
                response = await Client.SendAsync(request, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception ex) when (!(ex is OperationCanceledException))
            {
                return new TokenResponse(ex);
            }

On a more general note, I think wrapping exceptions at all is a mistake, because:
- it adds no value
- the exception can't be caught and/or filtered, it has to be examined via the `TokenResponse.Exception` property
- users typically won't expect that, and will try to catch an exception that will never actually be thrown (especially since it's not documented, users will probably assume the method can throw)

Of course, I realize that changing that would be a breaking change, but it would be nice to consider changing this for the next major version.

### PR DESCRIPTION
**Pull request by MatthewSteeples**
Fixes #176

I've gone through and handled all of the instances where an exception is serialized into a ProtocolResponse and ignored OperationCanceledException types.

I haven't done it the same as #176 suggested as I (personally) find this method easier to read. Happy to be overruled though

### CODE REVIEW

**Comment by brockallen** [comment]
Do you have any articles/docs on why OperationCanceledException is better or more appropriate than TaskCanceledException? TIA

**Comment by MatthewSteeples** [comment]
That's a good point. They probably both want excluding. It's not really a case of what's better, it's just what is likely to get thrown.

As a side note, it's good practice for Async methods to accept CancellationTokens and pass them on to things that they call

**Comment by leastprivilege** [comment]
You are supposed to handle OperationCancelledException which is the base class for TaskCancelledException.

Thanks!

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
