### PR TITLE
Reduction number of lock acquisitions in AccessTokenHandler and Acces…

### PR DESCRIPTION
**Pull request by adcy**
…sTokenDelegatingHandler 
#162

### CODE REVIEW

**Comment by leastprivilege** [comment]
@damianh

**Comment by adcy** [comment]
Hi! Any news?

**Comment by damianh** [comment]
Will take a peek this week.

**Comment by adcy** [comment]
> Will take a peek this week.

Could look on this?

**Comment by adcy** [comment]
Hi @damianh could you review this pr, please? Work of our command hanging while this bug not fixed.

**Comment by leastprivilege** [comment]
I am not a threading expert and don't have the time to look into it. The current v4 has removed the handler classes altogether until a better design has been found.

I recommend you copy the class into your code base and make the necessary changes yourself.

**Comment by leastprivilege** [comment]
@damianh if you don't have time for this, it's OK - let me know and I will close

**Pull request closed without merging**
