### PR TITLE
Use System.Text.Json

### PR DESCRIPTION
**Pull request by stefannikolei**
Remove reference to Newtonsoft.Json and refactor to System.Text.Json

#286

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks! That's cool - but obviously a breaking change. Nevertheless I want to do that. 

I created a new branch `features/v5` - could you do the PR against that branch, please?

thanks!

**Comment by leastprivilege** [comment]
Can you create a new PR?

**Comment by stefannikolei** [comment]
@leastprivilege why? It is targeting the right branch, or not?

**Comment by leastprivilege** [comment]
oh sorry - I missed that.

thanks!

**Pull request merged**
