### PR TITLE
Bug - Not checking for duplicate entry if allowEmpty is true

### PR DESCRIPTION
**Pull request by mihirdilip**
Here is the proposed solution. I have not tested it myself but looks like it will work.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks. Would you mind adding some tests around this?

**Comment by mihirdilip** [comment]
> 
> 
> Thanks. Would you mind adding some tests around this?
@leastprivilege

I have added few tests around this. Since it is an internal static class I had to make it available for testing.

**Review by leastprivilege — APPROVED** [review]

**Comment by leastprivilege** [comment]
thanks!

**Comment by mihirdilip** [comment]
Thanks for accepting the request.

**Pull request merged**
