### PR TITLE
Threading workarounds for WebGL

### PR DESCRIPTION
**Pull request by Brice-xCIT**
This tentative PR features workarounds for threading issues on Unity/WebGL. As described in https://github.com/IdentityModel/IdentityModel/pull/181, WebGL is a single-threaded platform, for which Unity provides a SynchronizationContext that marshalls task continuations in the (single) main thread. 

On this platform ConfigureAwait(false) fails silently, and the whole continuation does not run. Given how unlikely it seems that this issue ever be solved Unity-side or .NET-side (https://issuetracker.unity3d.com/issues/webgl-task-awaited-with-task-dot-configureawait-false-does-not-continue-in-a-webgl-build), this PR offers a workaround by exposing a flag consumer code can use to opt-out of internal ConfigureAwait(false) calls: ```IdentityModel.Internal.TaskHelpers.CanConfigureAwaitFalse = false;```

Additionally, Task.Factory.StartNew (and Task.Run) also fail on WebGL, so a small compatible rewrite of AsyncLazy is provided in order to allow DiscoveryCache to work on this platform.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Wow - this is fucked up ;)

I am considering it - could you re-base, because since my last merge is has conflicts.

**Comment by Brice-xCIT** [comment]
Thanks, done!

**Comment by leastprivilege** [comment]
Hey 

any thoughts on my above comment?

**Comment by Brice-xCIT** [comment]
Hi @leastprivilege. I'm not sure which comment you are referring to. All I can see is the one about fixing conflicts.

**Comment by leastprivilege** [comment]
I started a review...

Screenshot 2019-06-04 12 14 18

**Comment by Brice-xCIT** [comment]
Oh, sweet! But sadly I don't see any comment yet :( in whichever tab I go to...
Maybe that's related to your comment still marked "Pending"?

(This said I can already answer to the particular comment on your screenshot; do you mean something like below? Why not. I just was reluctant to write platform-specific code, but this would not be the case.)

```
private static Task<T> GetTaskAsync(Func<Task<T>> taskFactory)
{
	if (TaskHelpers.CanConfigureAwaitFalse)
	{
		return Task<Task<T>>.Factory.StartNew(taskFactory).Unwrap();
	}
	else
	{
		return taskFactory();
	}
}
```

**Comment by leastprivilege** [comment]
yep - that's what I had in mind. To reduce the impact on "normal" platforms.

**Comment by Brice-xCIT** [comment]
Makes sense. Maybe there should be another internal property ``TaskHelpers.CanFactoryStartNew`` because I'm not sure if the ConfigureAwait and the StartNew issues are completely related; it may be that a weird platform has one but not the other. (Though when it comes to Unity/WebGL, both seem to be like they come from an inability to switch to a context outside of the main thread.)

**Comment by leastprivilege** [comment]
Do that.

**Comment by leastprivilege** [comment]
Can you finish that work so I can merge?

**Comment by Brice-xCIT** [comment]
Hi @leastprivilege I'm a in a bit of a sprint right now, but I'm planning to do this quick work in the coming weeks. Hope the wait is okay.

**Comment by leastprivilege** [comment]
I will release v4 in the coming days - either you make the required changes now - or they won't make it..

**Comment by Brice-xCIT** [comment]
OK, I'll do this asap.

**Comment by Brice-xCIT** [comment]
@leastprivilege It's done!

**Comment by leastprivilege** [comment]
cool. thanks!

**Pull request merged**
