### PR TITLE
Change data type from string to Uri

### LINKED ISSUE #386: Use Uri instead of string datatype
Use the `Uri` datatype instead of `string` where applicable. Such as for the `ClientUri`, `LogoUri`, `PolicyUri` and `TosUri` properties in the `DynamicClientRegistrationDocument` class.

### PR DESCRIPTION
**Pull request by vanillajonathan**
Changes the data type from `string` to `Uri`.

Instead of weakly typed string we use strongly-typed `Uri` that accurately conveys the underlying data and ensures proper data and semantics through validation of input.

Closes #386.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@leastprivilege I believe this CI might have failed because the Azure pipelines were down at that moment.
I think running it again would make the CI succeed.

**Comment by leastprivilege** [comment]
Thanks. That's a breaking change. We can consider this for the next major release.

**Comment by leastprivilege** [comment]
If you can resolve the conflicts *today*, I can put that into the v6 release

**Comment by vanillajonathan** [comment]
@leastprivilege Done!

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
