### PR TITLE
integrate build CLI with Bullseye

### PR DESCRIPTION
**Pull request by adamralph**
By integrating Bullseye with McMaster (using new API's from Bullseye 3.2.0), you get proper help from you build script, including your custom option (`--sign`) and all the Bullseye options:

image

### CODE REVIEW

**Comment by adamralph** [comment]
rebased

**Comment by adamralph** [comment]
Rebased and switched to Bullseye 3.2.0 RC 1.

**Comment by leastprivilege** [comment]
Reduce that to 1 line of code ;)

**Comment by adamralph** [comment]
I guess I could collapse it down more, but before I do, how about https://github.com/IdentityModel/IdentityModel/pull/313 instead?

**Comment by adamralph** [comment]
Withdrawing in favour of https://github.com/IdentityModel/IdentityModel/pull/313

**Pull request closed without merging**
